In [4]:
#creating a board 
chessboard = [[5,3,4,9,10,4,3,5],
         [1,1,1,1,1,1,1,1],
         [0,0,0,0,0,0,0,0],
         [0,0,0,0,0,0,0,0],
         [0,0,0,0,0,0,0,0],
         [0,0,0,0,0,0,0,0],
         [-1,-1,-1,-1,-1,-1,-1,-1],
         [-5,-3,-4,-9,-10,-4,-3,-5]

         
         ]

In [5]:
mateinone=[[5,3,4,0,10,0,3,5],
           [1,1,1,1,0,1,1,1],
           [0,0,0,0,0,0,0,0],
           [0,0,4,0,1,0,0,0],
           [0,0,0,0,-1,0,0,9],
           [0,0,-3,0,0,-3,0,0],
           [-1,-1,-1,-1,-1,-1,-1,-1],
           [-5,-0,-4,-9,-10,-4,0,-5]

         
         ]
mateintwo=[[5,3,4,9,10,4,3,5],
           [1,1,1,1,0,1,1,1],
           [0,0,0,0,0,0,0,0],
           [0,0,4,0,1,0,0,0],
           [0,0,0,0,-1,0,0,9],
           [0,0,-3,0,0,-3,0,0],
           [-1,-1,-1,-1,-1,-1,-1,-1],
           [-5,-0,-4,-9,-10,-4,0,-5]

         
         ]

In [6]:

from functions import *

In [7]:
def dividebothmoves(allmoves):
    whitemoves=[]
    blackmove=[]
    for move in allmoves:
        if move[0]>0:
            whitemoves.append(move)
        if move[0]<0:
            blackmove.append(move) 
    return whitemoves,blackmove        


   

     

    

In [8]:
dividebothmoves(calculate_all_moves(chessboard))

([(3, 0, 1, 2, 2),
  (3, 0, 1, 2, 0),
  (3, 0, 6, 2, 7),
  (3, 0, 6, 2, 5),
  (1, 1, 0, 2, 0),
  (1, 1, 0, 3, 0),
  (1, 1, 1, 2, 1),
  (1, 1, 1, 3, 1),
  (1, 1, 2, 2, 2),
  (1, 1, 2, 3, 2),
  (1, 1, 3, 2, 3),
  (1, 1, 3, 3, 3),
  (1, 1, 4, 2, 4),
  (1, 1, 4, 3, 4),
  (1, 1, 5, 2, 5),
  (1, 1, 5, 3, 5),
  (1, 1, 6, 2, 6),
  (1, 1, 6, 3, 6),
  (1, 1, 7, 2, 7),
  (1, 1, 7, 3, 7)],
 [(-1, 6, 0, 5, 0),
  (-1, 6, 0, 4, 0),
  (-1, 6, 1, 5, 1),
  (-1, 6, 1, 4, 1),
  (-1, 6, 2, 5, 2),
  (-1, 6, 2, 4, 2),
  (-1, 6, 3, 5, 3),
  (-1, 6, 3, 4, 3),
  (-1, 6, 4, 5, 4),
  (-1, 6, 4, 4, 4),
  (-1, 6, 5, 5, 5),
  (-1, 6, 5, 4, 5),
  (-1, 6, 6, 5, 6),
  (-1, 6, 6, 4, 6),
  (-1, 6, 7, 5, 7),
  (-1, 6, 7, 4, 7),
  (-3, 7, 1, 5, 2),
  (-3, 7, 1, 5, 0),
  (-3, 7, 6, 5, 7),
  (-3, 7, 6, 5, 5)])

In [9]:
import numpy as np

## Checkmate Function

This function checks if the current chess board position leads to checkmate.

### Parameters:
- **board**: The 8x8 chess board represented as a 2D list.
- **kingposition**: Tuple representing the position of the king on the board.
- **toggle**: Boolean value indicating whether it's white's turn (True) or black's turn (False).

### Returns:
- **True** if the current position is checkmate, **False** otherwise.

In [10]:
def ischeakmate(board,kingpostion,toggle):
    
    
    
    if toggle:
     for x in range(8):
        for y in range(8):
            piece_value = board[x][y]
            if piece_value<0:
                moves = possible_moves( x, y, board)
                for move in moves:
                  if (move[3],move[4])==kingpostion:
                     return False
               
     return True
           
            # Calculate possible moves for the piece at (x, y)
            
    else:  
        for x in range(8):
         for y in range(8):
            piece_value = board[x][y]
            if piece_value>0:
                moves = possible_moves( x, y, board)
                for move in moves:
                  if (move[3],move[4])==kingpostion:
                     return False
        return True
           
            # Calculate possible moves for the piece at (x, y)
              

## Set Board Function

This function updates the chess board based on a given move.

### Parameters:
- **board**: The current 8x8 chess board represented as a 2D list.
- **move**: A tuple containing information about the move - (piece, start_row, start_col, end_row, end_col).
- **boardlist**: A list containing historical board positions.

### Returns:
- Updated **board** after applying the move.

In [11]:
def setboard(board, move,boardlist):

    piece, start_row, start_col, end_row, end_col = move
    board[end_row][end_col] = piece
    board[start_row][start_col] = 0
    
    return board
    

def resetboard(board, boardlist):
    board=boardlist[-1]
    

 

In [12]:
value=np.zeros((4,5))
print(value)
value[0][1]=2
print(value)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


This function performs a series of chess-related calculations, evaluates the board position, and provides a multi-dimensional numpy array as the result.

### Parameters:
- **board**: The current 8x8 chess board represented as a 2D list.
- **toggle**: Boolean value indicating whether it's white's turn (True) or black's turn (False).

### Returns:
- If it's white's turn, returns a list of possible white moves and a numpy array representing the evaluation of the board.
- If it's black's turn, returns a list of possible black moves and a numpy array representing the evaluation of the board.

### Evaluation Array Structure:
- **[mate, numberofmovesforwhite, numberofmovesforblack, actualvalue, additionofpiceces]**
- **w [centre, quad1, quad2, quad3, quad4]**
- **b [centre, quad1, quad2, quad3, quad4]**
- **[movesforwhitequeen, movesforwhiterook, movesforwhiteknight, movesforbishop, movesforwhiteking]**
- **[movesforblackqueen, movesforblackrook, movesforblackknight, movesforblackbishop, movesforblackking]**
- **[movesforwhitepawn, moveforblackpawn, whitecapturingmove, blackcaptureingmove, ischeak]**


In [56]:
def allinonefuntion(board,toggle):
    """
    calculatemoves
    flitermoves
    dividemoves 
    is king in cheak for white and black 
    give value 



    create a numpy array for give value 
    [[mate, numberofmovesforwhite,numberofmovesforblack,actualvalue,,additionofpiceces],
   w [centre,quad1,quad2,quad3,quad4],
    b[centre,quad1,quad2,quad3,quad4],
     [movesforwhitequeen,movesforwhiterook,movesforwhiteknight,movesforbishop,movesforwhiteking ]
     [movesforblackqueen,movesforblackrook,movesforblackknight,movesforblackbishop,movesforblackking ]
     [movesforwhitepawn,moveforblackpawn,whitecapturingmove,blackcaptureingmove,0]
     

    ]
    
    
    
    
    
    
    """
    value=np.zeros((6,5))
    boardlist=[]
    quadrants = {
    0: [[2, 5], [2, 5]],
    1: [[0, 3], [0, 3]],
    2: [[0, 3], [4, 7]],
    3: [[4, 7], [0, 3]],
    4: [[4, 7], [4, 7]]
}
    boardlist.append(board)
    
    boardtotal=0
    moves=calculate_all_moves(board)
    newMoves=[]
    white=[]
    black=[]
    board_copy = [row[:] for row in board]
    for row in range(8):
        for col in range(8):
            boardtotal+=  board[row][col]
            if board[row][col] == 10:  # White king is represented by 10
                white_king_position = (row, col)
            elif   board[row][col] == -10: 
                black_king_position = (row, col)

    value[0][4]=boardtotal
    if True:
        for move in moves:
            if move[0]>0:
               
               board_copy = [row[:] for row in board]
               board_copy=setboard(board_copy,move,boardlist)
               boardlist.append(board_copy)
               if move[0]==10:
                   new_white_king_position =(move[3],move[4])
                   if ischeakmate(board_copy,new_white_king_position,True):
                      value[0][1]+=1
                      value[3][4]+=1
                      resetboard(board_copy,boardlist)
              
                      white.append(move)
                        
               elif ischeakmate(board_copy,white_king_position,True):
                   resetboard(board_copy,boardlist)
                   value[0][1]+=1
                   if board[move[3]][move[4]]<0:
                       value[5][3]+=1
              
                   white.append(move)
                   if move[0]==9:
                       value[3][0]+=1
                       for quadrant in quadrants:
                          x_condition, y_condition = quadrants[quadrant]
                          if x_condition[0] <= move[3] <= x_condition[1] and y_condition[0] <= move[4] <= y_condition[1]:
                              value[1][quadrant] += 1
                      
                   elif move[0] ==5:
                       value[3][1]+=1
                       for quadrant in quadrants:
                          x_condition, y_condition = quadrants[quadrant]
                          if x_condition[0] <= move[3] <= x_condition[1] and y_condition[0] <= move[4] <= y_condition[1]:
                              value[1][quadrant] += 1
                   elif move[0] ==4:
                       value[3][2]+=1
                       for quadrant in quadrants:
                          x_condition, y_condition = quadrants[quadrant]
                          if x_condition[0] <= move[3] <= x_condition[1] and y_condition[0] <= move[4] <= y_condition[1]:
                              value[1][quadrant] += 1
                   elif move[0] ==3:
                       value[3][3]+=1
                       for quadrant in quadrants:
                          x_condition, y_condition = quadrants[quadrant]
                          if x_condition[0] <= move[3] <= x_condition[1] and y_condition[0] <= move[4] <= y_condition[1]:
                              value[1][quadrant] += 1
                   elif move[0] ==1:
                       value[5][0]+=1
                       for quadrant in quadrants:
                          x_condition, y_condition = quadrants[quadrant]
                          if x_condition[0] <= move[3] <= x_condition[1] and y_condition[0] <= move[4] <= y_condition[1]:
                              value[1][quadrant] += 1
            else:#black 
                board_copy =  [row[:] for row in board]      
                board_copy=setboard(board_copy,move,boardlist)
                
                
                if move[0]==-10:
                   new_black_king_position =(move[3],move[4])
                   if ischeakmate(board_copy,new_black_king_position,False):
                      value[0][2]+=1
                      value[4][4]+=1
                      resetboard(board_copy,boardlist)
              
                      black.append(move)
                        
                elif ischeakmate(board_copy,black_king_position,False):
                    resetboard(board_copy,boardlist)
                    value[0][2]+=1
                    if board[move[3]][move[4]]>0:
                        value[5][2]+=1
              
                    black.append(move)
                    if move[0]==-9:
                       value[4][0]+=1
                       for quadrant in quadrants:
                          x_condition, y_condition = quadrants[quadrant]
                          if x_condition[0] <= move[3] <= x_condition[1] and y_condition[0] <= move[4] <= y_condition[1]:
                              value[2][quadrant] += 1
                      
                    elif move[0] ==-5:
                       value[4][1]+=1
                       for quadrant in quadrants:
                          x_condition, y_condition = quadrants[quadrant]
                          if x_condition[0] <= move[3] <= x_condition[1] and y_condition[0] <= move[4] <= y_condition[1]:
                              value[2][quadrant] += 1
                    elif move[0] ==-4:
                       value[4][2]+=1
                       for quadrant in quadrants:
                          x_condition, y_condition = quadrants[quadrant]
                          if x_condition[0] <= move[3] <= x_condition[1] and y_condition[0] <= move[4] <= y_condition[1]:
                              value[2][quadrant] += 1
                    elif move[0] ==-3:
                       value[4][3]+=1
                       for quadrant in quadrants:
                          x_condition, y_condition = quadrants[quadrant]
                          if x_condition[0] <= move[3] <= x_condition[1] and y_condition[0] <= move[4] <= y_condition[1]:
                              value[2][quadrant] += 1
                    elif move[0] ==-1:
                       value[5][1]+=1
                       for quadrant in quadrants:
                          x_condition, y_condition = quadrants[quadrant]
                          if x_condition[0] <= move[3] <= x_condition[1] and y_condition[0] <= move[4] <= y_condition[1]:
                              value[2][quadrant] += 1             
  #  print(value)
    if toggle and not ischeakmate(board,white_king_position,True) :
       value[5][4]=-1
       if white==[]:
        value[0][0]=-1
        value[0][3]=-1000

    elif not toggle and not ischeakmate(board,black_king_position,False) : 
         
        value[5][4]=1
        if black==[]:
          value[0][0]=1
          value[0][3]=1000
    else:      
       value[0][3]=value[0][1]- value[0][2]  +value[0][4] +value[1][0] +value[1][1]+value[1][2]+value[1][3]+value[1][4]  -value[2][0] -value[2][1]-value[2][2]-value[2][3]-value[2][4] +value[3][0] +value[3][1]+value[3][2]+value[3][3]+value[3][4] +value[5][0]- value[4][0] -value[4][1]-value[4][2]-value[4][3]-value[4][4] -value[5][1]+value[5][2] - value[5][3] + 100*value[5][4]

   # print(value)
    if toggle:
        return white,value
    else:
          return black,value














         

    

In [55]:
chessboard = [[5,3,4,9,10,4,3,5],
             [1,1,1,1,0,1,1,1],
             [0,0,0,0,0,0,0,0],
             [0,0,0,0,1,0,0,0],
             [0,0,0,0,-1,0,0,0],
             [0,0,0,0,0,0,0,0],
         [-1,-1,-1,-1,0,-1,-1,-1],
         [-5,-3,-4,-9,-10,-4,-3,-5]

         
         ]
ans=allinonefuntion(chessboard,True)
print(ans[1])


[[ 0. 29. 29.  0.  0.]
 [11. 12. 13.  2.  1.]
 [11.  2.  1. 12. 13.]
 [ 4.  0.  5.  5.  1.]
 [ 4.  0.  5.  5.  1.]
 [14. 14.  0.  0.  0.]]


In [15]:
import copy
def simulate_move(board, move):
    piece, start_row, start_col, end_row, end_col = move
    board[end_row][end_col] = piece
    board[start_row][start_col] = 0
    
    return  board

In [16]:
memory={}

  Recursive function to evaluate the chess board and find the best move.

    Parameters:
    - **board**: The current 8x8 chess board represented as a 2D list.
    - **toggle**: Boolean value indicating whether it's white's turn (True) or black's turn (False).
    - **depth**: The depth of the recursion.
    - **boardlist**: A list containing historical board positions.

    Returns:
    - A tuple containing the evaluation value and a dictionary of possible moves with their corresponding values.

In [51]:

#@my_lru_cache
memory={}
memo={}
def recursionfunction(board,toggle ,deapth,boardlist):
    board_key = tuple(map(tuple, board))
    movetable={}
    if board_key in memo:
        print("iss")
        return memo[board_key],{}
    
    if deapth==0:
        moves,value=allinonefuntion(board,toggle)
        memo[board_key] =  value[0][3]   
        return value[0][3],{}
    if boardlist==[]:
        boardlist.append(copy.deepcopy(board))
    
    if toggle:
        white,value=allinonefuntion(board,True)
        if value[0][0]==1:
            return 1000,{}
        for move in white:
            board_copy=copy.deepcopy(boardlist[-1])
            #print(boardlist)
            board_copy= simulate_move(board_copy,move)
            
            boardlist.append(copy.deepcopy(board_copy))
            print(board_copy)
           # moves,value[0][4]=allinonefuntion(board,toggle)
            valueone= recursionfunction(board_copy,not toggle,deapth-1,boardlist)
            
            boardlist.pop(-1)
            
          #  print(boardlist)
            board_copy=boardlist[-1]
            value[0][3]= (value[0][3]+ valueone[0])/len(white)
            movetable[move]= value[0][3]
            
            
        #return value[0][3]
          #  print(boardlist)
    if not toggle:
       
        black,value=allinonefuntion(board,False)
        if value[0][0]==-1:
            return -1000,{}
        for move in black:
            board_copy=copy.deepcopy(boardlist[-1])
           # print(board_copy)
            board_copy= simulate_move(board_copy,move)
            
            boardlist.append(copy.deepcopy(board_copy))
            print(board_copy)
           # moves,value=allinonefuntion(board,toggle)
            valueone= recursionfunction(board_copy,not toggle,deapth-1,boardlist)
            boardlist.pop(-1)
            #print(boardlist)
            board_copy=boardlist[-1]
           # print(boardlist)
            value[0][3]= (value[0][3]+ valueone[0])/len(black)
            movetable[move]= value[0][3]
            
    memo[board_key] =  value[0][3]      
    return value[0][3],movetable

            
            

In [38]:
chessboard = [[5,3,4,9,10,4,3,5],
         [1,1,1,1,1,1,1,1],
         [0,0,0,0,0,0,0,0],
         [0,0,0,0,0,0,0,0],
         [0,0,0,0,0,0,0,0],
         [0,0,0,0,0,0,0,0],
         [-1,-1,-1,-1,-1,-1,-1,-1],
         [-5,-3,-4,-9,-10,-4,-3,-5]

         
         ]
recursionfunction(chessboard,True,2,[])

[[5, 0, 4, 9, 10, 4, 3, 5], [1, 1, 1, 1, 1, 1, 1, 1], [0, 0, 3, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [-1, -1, -1, -1, -1, -1, -1, -1], [-5, -3, -4, -9, -10, -4, -3, -5]]
[[5, 0, 4, 9, 10, 4, 3, 5], [1, 1, 1, 1, 1, 1, 1, 1], [0, 0, 3, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [-1, 0, 0, 0, 0, 0, 0, 0], [0, -1, -1, -1, -1, -1, -1, -1], [-5, -3, -4, -9, -10, -4, -3, -5]]
[[5, 0, 4, 9, 10, 4, 3, 5], [1, 1, 1, 1, 1, 1, 1, 1], [0, 0, 3, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [-1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, -1, -1, -1, -1, -1, -1, -1], [-5, -3, -4, -9, -10, -4, -3, -5]]
[[5, 0, 4, 9, 10, 4, 3, 5], [1, 1, 1, 1, 1, 1, 1, 1], [0, 0, 3, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, -1, 0, 0, 0, 0, 0, 0], [-1, 0, -1, -1, -1, -1, -1, -1], [-5, -3, -4, -9, -10, -4, -3, -5]]
[[5, 0, 4, 9, 10, 4, 3, 5], [1, 1, 1, 1, 1, 1, 1, 1], [0, 0, 3, 0, 0, 0, 0, 0], [0, 0, 0, 0,

(-0.016574442005835337,
 {(3, 0, 1, 2, 2): 0.0007876033722355605,
  (3, 0, 1, 2, 0): -0.014962490143362933,
  (3, 0, 6, 2, 7): -0.015749994858205614,
  (3, 0, 6, 2, 5): 1.0359026253632664e-07,
  (1, 1, 0, 2, 0): -0.030791338816672103,
  (1, 1, 0, 3, 0): -0.016541437252808572,
  (1, 1, 1, 2, 1): -0.015828942174615397,
  (1, 1, 1, 3, 1): -0.01578675492070471,
  (1, 1, 2, 2, 2): -0.02105436595274704,
  (1, 1, 2, 3, 2): -0.010791430714875476,
  (1, 1, 3, 2, 3): 0.03170197826741285,
  (1, 1, 3, 3, 3): 0.04435327700600093,
  (1, 1, 4, 2, 4): 0.06089373843964087,
  (1, 1, 4, 3, 4): 0.06422076151132286,
  (1, 1, 5, 2, 5): -0.03547504276272461,
  (1, 1, 5, 3, 5): -0.029933517226015803,
  (1, 1, 6, 2, 6): -0.016498546173275754,
  (1, 1, 6, 3, 6): -0.013201797620541092,
  (1, 1, 7, 2, 7): -0.031451433877212547,
  (1, 1, 7, 3, 7): -0.016574442005835337})

In [52]:
mateinthree=[[0,0,0,0,0,9,0,0],
[0,-9,0,0,0,1,10,0],
[0,0,0,0,-4,1,0,1],
[0,0,0,0,0,0,0,0],
[0,0,0,0,0,-1,-1,0],
[0,0,0,0,0,0,0,4],
[0,0,0,0,0,0,0,-1],
[0,0,0,0,0,0,-10,0]]
ans=recursionfunction(mateinone,True,1,[])


[[5, 0, 4, 0, 10, 0, 3, 5], [1, 1, 1, 1, 0, 1, 1, 1], [0, 0, 3, 0, 0, 0, 0, 0], [0, 0, 4, 0, 1, 0, 0, 0], [0, 0, 0, 0, -1, 0, 0, 9], [0, 0, -3, 0, 0, -3, 0, 0], [-1, -1, -1, -1, -1, -1, -1, -1], [-5, 0, -4, -9, -10, -4, 0, -5]]
[[5, 0, 4, 0, 10, 0, 3, 5], [1, 1, 1, 1, 0, 1, 1, 1], [3, 0, 0, 0, 0, 0, 0, 0], [0, 0, 4, 0, 1, 0, 0, 0], [0, 0, 0, 0, -1, 0, 0, 9], [0, 0, -3, 0, 0, -3, 0, 0], [-1, -1, -1, -1, -1, -1, -1, -1], [-5, 0, -4, -9, -10, -4, 0, -5]]
[[5, 3, 4, 10, 0, 0, 3, 5], [1, 1, 1, 1, 0, 1, 1, 1], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 4, 0, 1, 0, 0, 0], [0, 0, 0, 0, -1, 0, 0, 9], [0, 0, -3, 0, 0, -3, 0, 0], [-1, -1, -1, -1, -1, -1, -1, -1], [-5, 0, -4, -9, -10, -4, 0, -5]]
[[5, 3, 4, 0, 0, 10, 3, 5], [1, 1, 1, 1, 0, 1, 1, 1], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 4, 0, 1, 0, 0, 0], [0, 0, 0, 0, -1, 0, 0, 9], [0, 0, -3, 0, 0, -3, 0, 0], [-1, -1, -1, -1, -1, -1, -1, -1], [-5, 0, -4, -9, -10, -4, 0, -5]]
[[5, 3, 4, 0, 0, 0, 3, 5], [1, 1, 1, 1, 10, 1, 1, 1], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 4

In [43]:
print(len(memo))

5499


 Find the best move from the provided move table.

    Parameters:
    - **movetable**: A dictionary containing possible moves with their corresponding values.

    Returns:
    - The best move with the highest value.

In [49]:
def best_move(movetable):
    max_key = max(movetable, key=movetable.get)
    return max_key


In [54]:
best_move(ans[1])
print(ans[1])

{(3, 0, 1, 2, 2): 3.186046511627907, (3, 0, 1, 2, 0): 1.5159545700378583, (10, 0, 4, 0, 3): 1.3840919667450664, (10, 0, 4, 0, 5): 1.3810253945754667, (10, 0, 4, 1, 4): 1.287930823129662, (3, 0, 6, 2, 7): 1.495068158677434, (3, 0, 6, 2, 5): 1.4533736781087776, (3, 0, 6, 1, 4): 1.4989156669327621, (1, 1, 0, 2, 0): 1.4999747829519245, (1, 1, 0, 3, 0): 1.6395342972779516, (1, 1, 1, 2, 1): 1.5032449836576267, (1, 1, 1, 3, 1): 1.5930987205501772, (1, 1, 2, 2, 2): 1.3161185748965156, (1, 1, 3, 2, 3): 1.6817701994161982, (1, 1, 3, 3, 3): 1.9460876790561905, (1, 1, 5, 2, 5): 1.1382811088152602, (1, 1, 5, 3, 5): 1.445076304856169, (1, 1, 6, 2, 6): 1.428955262903632, (1, 1, 6, 3, 6): 1.149510587509387, (1, 1, 7, 2, 7): 1.3523141997095207, (1, 1, 7, 3, 7): 1.3570305627839423, (4, 3, 2, 4, 3): 1.403651873553115, (4, 3, 2, 5, 4): 1.5210151598500725, (4, 3, 2, 6, 5): 23.29118639906628, (4, 3, 2, 4, 1): 2.0300275906759597, (4, 3, 2, 5, 0): 1.396047153271534, (4, 3, 2, 2, 3): 1.1952569105411983, (4, 3,